### ISSUE TITLE
有些文件夹里的图片无法显示

### ISSUE THREAD

**Issue by netdog2019** [zuoez02/siyuan-plugin-picture-library#1]
我把原有的照片用软链接的方式连接到该目录下，发现有很多文件夹打开是空的，但是实际上该文件夹里是有图片的。不知为何。感谢大佬的插件~~~

**Comment by zuoez02** [comment]
对图片格式做了限制，你显示不出来的图片格式是什么？

**Comment by zuoez02** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/Media/Formats/Image_types

**Comment by Achuan-2** [comment]
我相机导出的图片是大写JPG，并不能显示，需要改后缀
![image](https://github.com/zuoez02/siyuan-plugin-picture-library/assets/60436214/103a89a5-2271-4c30-89b0-e47064ddb0a4)

**Comment by netdog2019** [comment]
我得也是JPG，大写的，无法显示

**Comment by zuoez02** [comment]
v0.1.1已修复
