### ISSUE TITLE
卡顿

### ISSUE THREAD

**Issue by DionathanJoestar** [zuoez02/siyuan-plugin-picture-library#14]
一个不知道算不算bug的问题，我的文件夹80+张图片。加载和滑动滚轮非常卡

**Comment by zuoez02** [comment]
是图片特别大吗？可能大图片确实会卡一些吧

**Comment by DionathanJoestar** [comment]
> 是图片特别大吗？可能大图片确实会卡一些吧

再问一嘴，我看到文件的存档位置是在data文件夹以外，不能多端同步么？

**Comment by zuoez02** [comment]
在data里，多端同步的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: DionathanJoestar ***@***.***>
发送时间: Saturday, December 23, 2023 12:04:14 PM
收件人: zuoez02/siyuan-plugin-picture-library ***@***.***>
抄送: Luto Yvan ***@***.***>; Comment ***@***.***>
主题: Re: [zuoez02/siyuan-plugin-picture-library] 卡顿 (Issue #14)


是图片特别大吗？可能大图片确实会卡一些吧

再问一嘴，我看到文件的存档位置是在data文件夹以外，不能多端同步么？

―
