### ISSUE TITLE
Dock中文件夹 滚动显示内容？

### ISSUE THREAD

**Issue by xuguangjian** [zuoez02/siyuan-plugin-picture-library#2]
这里文档中说：跑马灯
点击Dock中文件夹的第一个按钮“复制跑马灯”
在文档中粘贴即可生成跑马灯，滚动显示内容

![image](https://github.com/zuoez02/siyuan-plugin-picture-library/assets/66892415/e141f687-e2c5-4ab0-a866-2f1ced5f67ef)
我都找完了也没找到按钮，怎么滚动显示内容？

**Comment by zuoez02** [comment]
对。就这个展示面板


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: xuguangjian ***@***.***>
发送时间: Friday, August 11, 2023 8:15:31 AM
收件人: zuoez02/siyuan-plugin-picture-library ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zuoez02/siyuan-plugin-picture-library] Dock中文件夹 滚动显示内容？ (Issue #2)


这里文档中说：跑马灯
点击Dock中文件夹的第一个按钮“复制跑马灯”
在文档中粘贴即可生成跑马灯，滚动显示内容

[image]<https://user-images.githubusercontent.com/66892415/259899208-e141f687-e2c5-4ab0-a866-2f1ced5f67ef.png>
我都找完了也没找到按钮，怎么滚动显示内容？

―

**Comment by xuguangjian** [comment]
找到了，是我的问题，文件夹里我只加了一张照片，不错，这个很有意思
![image](https://github.com/zuoez02/siyuan-plugin-picture-library/assets/66892415/7eb95611-396a-49ca-ab2a-84b16711b3b7)
