### ISSUE TITLE
能否修改下插件图标，现在感觉有点不搭配

### ISSUE THREAD

**Issue by lsb226** [zuoez02/siyuan-plugin-picture-library#3]
![image](https://github.com/zuoez02/siyuan-plugin-picture-library/assets/16093704/634fe456-b8b2-4956-8530-c9696eb41a89)

**Comment by lsb226** [comment]
上面的另一个是markming 思维导图插件，感觉跟思源挺搭配的

**Comment by zuoez02** [comment]
Resolved
