### ISSUE TITLE
点击“展示面板”HTML块的编辑按钮后，该块退出图片展示模式

### ISSUE THREAD

**Issue by fenshen000** [zuoez02/siyuan-plugin-picture-library#6]
有点难描述。。
在文档中点击复制过来的“展示面板”右上角的“编辑按钮”
![image](https://github.com/zuoez02/siyuan-plugin-picture-library/assets/43239563/bc636a40-d54a-439d-8053-a8fe39845f08)
虽然并未修改HTML代码，但退出编辑模式后，该HTML块会自动退出图片展示模式，只显示一行字：
![image](https://github.com/zuoez02/siyuan-plugin-picture-library/assets/43239563/c6c6b9e2-0af3-4750-8a7a-377d703bbdbc)
虽然说，重启思源笔记后，该HTML块也会恢复到正常的展示状态，但总还是会有点影响观看体验。。。特别是不小心误触的话，可能会以为该HTML块失效

**Comment by zuoez02** [comment]
目前没有什么办法，HTML块只能说是自定义块的临时替代品，先将就用吧。后面思源支持正确的“自定义块”之后我们再考虑如何处理
