### ISSUE TITLE
能不能支持下新版2.10+

### ISSUE THREAD

**Issue by liuyanfight** [zuoez02/siyuan-plugin-picture-library#7]
当前版本2.10.1现实不兼容，右上角Dock也找不到图库

**Comment by zuoez02** [comment]
2.10.6我这正常，你重启一下思源试试？确认你开启了此插件哈。

**Comment by liuyanfight** [comment]
> 2.10.6我这正常，你重启一下思源试试？确认你开启了此插件哈。

难道是因为我用的docker版的缘故？
![image](https://github.com/zuoez02/siyuan-plugin-picture-library/assets/6874266/2e338562-b7b3-4ad9-a433-26138c098fca)

**Comment by zuoez02** [comment]
对的，docker版本不兼容
